name: Web Crawler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
      - name: Run web crawler
        run: |
          python -m lib.webcrawl
          echo "resul<<EOF" >> $GITHUB_OUTPUT
          cat output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Send Email
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: "CMS Connectivity Test - ${{ steps.crawler.outputs.status }}"
          to: pohxiang.yeoh@hiredly.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            CMS Connectivity Test Results
            
            Status: ${{ steps.crawler.outputs.status }}
            Test URL: https://my.hiredly.com/about-us
            CMS URL: https://cms.hiredly.com
            Timestamp: $(date)
            
            Full Test Output:
            $(cat crawler_output.txt)
            
            View full logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
