name: Web Crawler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install
      - name: Run web crawler
        id: crawler
        run: |
          python -m lib.webcrawl | tee crawler_output.txt
          
          # Check if test passed or failed
          if grep -q "RESULT: PASS" crawler_output.txt; then
            echo "status=PASS" >> $GITHUB_OUTPUT
          else
            echo "status=FAIL" >> $GITHUB_OUTPUT
          fi
          
          # Store output for email
          echo "output<<EOF" >> $GITHUB_OUTPUT
          cat crawler_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          
      - name: Send Email
        if: steps.crawler.outputs.status == 'FAIL'
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: "CMS Connectivity Test - FAILED"
          to: engineering@hiredly.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            CMS Connectivity Test Results
            
            Status: FAILED
            Test URL: https://my.hiredly.com/about-us
            CMS URL: https://cms.hiredly.com
            
            Full Test Output:
            ${{ steps.crawler.outputs.output }}
            
            View full logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}